### ISSUE TITLE
Upgrade to ZIO 2.0

### ISSUE THREAD

**Issue by swoogles** [gaelrenoux/tranzactio#32]
ZIO 2.0 is at Milestone 4, with an RC expected in the next few weeks.
https://github.com/zio/zio/releases/tag/v2.0.0-M4

The API is nearly stable at this point, so any early migration work against this version should pay off towards the official 2.0 release.

The progress is being tracked here:
zio/zio#5470

The Stream Encoding work in progress is the only area where the API might still change before the RC.

We are actively working on a ScalaFix rule that will cover the bulk of the simple API changes:
https://github.com/zio/zio/blob/series/2.x/scalafix/rules/src/main/scala/fix/Zio2Upgrade.scala
We highly recommend starting with that, and then working through any remaining compilation errors :)

To assist with the rest of the migration, we have created this guide:
https://zio.dev/howto/migrate/zio-2.x-migration-guide/

If you would like assistance with the migration from myself or other ZIO contributors, please let us know!

**Comment by peterstorm** [comment]
Anyone timeline on this upgrade? :)

**Comment by gaelrenoux** [comment]
Hey, so little update: I'm currently in the process of moving to a new city, meaning I have very little time these days. I plan to work on this after I've moved, but don't expect anything before April. If someone's willing to start working on this, I completely welcome it.

**Comment by swoogles** [comment]
> Hey, so little update: I'm currently in the process of moving to a new city, meaning I have very little time these days. I plan to work on this after I've moved, but don't expect anything before April. If someone's willing to start working on this, I completely welcome it.

Thanks for the update. I will try to execute the ScalaFix migration rule against the project, but if it requires deeper migration work, I probably can't focus on it anytime soon either.

**Comment by swoogles** [comment]
> Hi @swoogles and @gaelrenoux
> 
> @peterstorm and I have overhauled tranzactio :tractor:  to get it to work with ZIO 2.0 
> 
> Both of us are new to ZIO 2 and to the tranzactio so we would like a first impression sanity check.
> 
> 

Great! Is there a branch to check out?

**Comment by swoogles** [comment]
> Hi @swoogles and @gaelrenoux
> 
> @peterstorm and I have overhauled tranzactio :tractor:  to get it to work with ZIO 2.0 
> 
> Both of us are new to ZIO 2 and to the tranzactio so we would like a first impression sanity check.
> 
> 

Great! Is there a branch to check out?

**Comment by pellekrogholt** [comment]
@swoogles yes its in the pr https://github.com/gaelrenoux/tranzactio/pull/36 > https://github.com/undo-insurance/tranzactio/tree/fix-onbound-wildcard-type

**Comment by swoogles** [comment]
@pellekrogholt Submitted a PR to your PR branch with a few changes :)

**Comment by pellekrogholt** [comment]
@swoogles thx its merged into the branch and the rest of the issues are fixed :crossed_fingers: 

Peter and I will have a last look later today :sun_with_face:

**Comment by pellekrogholt** [comment]
@gaelrenoux we have wrapped up the ZIO 2.0 upgrade pr https://github.com/gaelrenoux/tranzactio/pull/36 > https://github.com/undo-insurance/tranzactio/tree/fix-onbound-wildcard-type

we are down to 2 warnings in the DoobieIT test: 

```
a type was inferred to be `Any`; this may indicate a programming error. 
```

line 58 and 66 - which is weird because line  74 has no warning.

Lets us know if these warnings are show stoppers for you.

Lastly also let us know if branch name and commits are important...

**Comment by pellekrogholt** [comment]
After a closer look and feedback .... the compiler warning can be ignored https://github.com/gaelrenoux/tranzactio/pull/36#issuecomment-1059001063

**Comment by pellekrogholt** [comment]
@gaelrenoux have you had a chance to look at our PR? we are eager to have the effort used and would also like to use tranzactio with ZIO 2 for some upcoming projects :smile_cat:

**Comment by gaelrenoux** [comment]
I've merged your PR to go to the RC2 version, then did the necessary changes up to RC5. I'll keep this issue open until we have the definitive 2.0.0 ZIO version.

**Comment by ex0ns** [comment]
Hi, is it possible for you to release a version compatible with the RC6  ? This should hopefully be the last one before the final release (according to zio channel on discord).

That would be amazing to prepare the upcoming 2.0 release.

Thanks

**Comment by gaelrenoux** [comment]
Yup, done. I've published 4.0.0-M4 for the RC6 of ZIO. `ZTraceElement`s were actually the easiest change. I was more annoyed by stuff that wasn't mentioned in the release note (renaming `layer` into `bootstrap`, the disappearance of the `ZSpec` type…)

**Comment by swoogles** [comment]
Thanks for working on the upgrade @gaelrenoux !
It's showing up on the ecosystem tracker 🙂 
<img width="1101" alt="Screen Shot 2022-06-19 at 9 49 23 AM" src="https://user-images.githubusercontent.com/2054940/174489491-eb11d50d-05cd-475d-b83a-a9b7991d51e0.png">

Are there any other bits that you can remember from that `...` ? We'd like to improve the coverage of release notes/docs as much as possible

**Comment by gaelrenoux** [comment]
Aaaaaand upgraded to ZIO 2.0.0!
